apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docs
  namespace: argocd
spec:
  project: workshop
  source:
    repoURL: https://github.com/ricCap/crossplane-workshop.git
    targetRevision: main
    path: gitops/docs
  destination:
    server: https://kubernetes.default.svc
    namespace: docs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
